///*
// * To change this template, choose Tools | Templates
// * and open the template in the editor.
// */
//package ebooksaver;
//
//import java.awt.Point;
//import java.awt.Rectangle;
//import java.util.Arrays;
//import java.util.Comparator;
//import java.util.regex.Pattern;
//import javax.imageio.ImageIO;
//import javax.swing.DefaultComboBoxModel;
//import javax.swing.JFileChooser;
//
///**
// *
// * @author John
// */
//public final class Menu extends javax.swing.JFrame {
//
//	private Point clickLoc = new Point(-1, -1);
//	private final DefaultComboBoxModel model;
//
//	/**
//	 * Creates new form Menu
//	 */
//	public Menu() {
//		String[] fileTypes = ImageIO.getReaderFormatNames();
//		Arrays.sort(fileTypes, new Comparator<String>() {
//
//			@Override
//			public int compare(String o1, String o2) {
//				return o1.toLowerCase().compareTo(o2.toLowerCase());
//			}
//		});
//		model = new DefaultComboBoxModel(fileTypes);
//		initComponents();
//		cSavePath.setText(System.getProperty("user.home"));
//	}
//        
//        
//
//	public void setWindow(Rectangle window) {
//		cWindow.setText(window.x + ", " + window.y + ", " + window.width + ", "
//				+ window.height);
//	}
//
//	public Point getDocLocation() {
//		return mouseDoc.getLocationOnScreen();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        dragFrom = new javax.swing.JPanel();
//        cClickPosition = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        mouseDoc = new javax.swing.JPanel();
//        jLabel3 = new javax.swing.JLabel();
//        change = new javax.swing.JButton();
//        jLabel4 = new javax.swing.JLabel();
//        cSavePath = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        overwrite = new javax.swing.JCheckBox();
//        jButton1 = new javax.swing.JButton();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        cWindow = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        waitTime = new javax.swing.JTextField();
//        jCheckBox1 = new javax.swing.JCheckBox();
//        jLabel9 = new javax.swing.JLabel();
//        jButton2 = new javax.swing.JButton();
//        jLabel10 = new javax.swing.JLabel();
//        name = new javax.swing.JTextField();
//        jLabel11 = new javax.swing.JLabel();
//        checkForDuplicates = new javax.swing.JCheckBox();
//        jLabel12 = new javax.swing.JLabel();
//        jComboBox1 = new javax.swing.JComboBox();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        dragFrom.setBackground(new java.awt.Color(255, 255, 255));
//        dragFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        dragFrom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
//            public void mouseDragged(java.awt.event.MouseEvent evt) {
//                dragFromMouseDragged(evt);
//            }
//        });
//
//        javax.swing.GroupLayout dragFromLayout = new javax.swing.GroupLayout(dragFrom);
//        dragFrom.setLayout(dragFromLayout);
//        dragFromLayout.setHorizontalGroup(
//            dragFromLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 22, Short.MAX_VALUE)
//        );
//        dragFromLayout.setVerticalGroup(
//            dragFromLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 16, Short.MAX_VALUE)
//        );
//
//        cClickPosition.setText("-1,-1");
//
//        jLabel2.setText("Place to click to turn the page:");
//
//        mouseDoc.setBackground(new java.awt.Color(255, 255, 255));
//        mouseDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        javax.swing.GroupLayout mouseDocLayout = new javax.swing.GroupLayout(mouseDoc);
//        mouseDoc.setLayout(mouseDocLayout);
//        mouseDocLayout.setHorizontalGroup(
//            mouseDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 22, Short.MAX_VALUE)
//        );
//        mouseDocLayout.setVerticalGroup(
//            mouseDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 16, Short.MAX_VALUE)
//        );
//
//        jLabel3.setText("(Drag mouse from box to change)");
//
//        change.setText("Change...");
//        change.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                changeActionPerformed(evt);
//            }
//        });
//
//        jLabel4.setText("Save Images To:");
//
//        jLabel1.setText("Mouse Doc:");
//
//        overwrite.setSelected(true);
//        overwrite.setText("Overwrite Previous Images");
//
//        jButton1.setText("Start!");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jLabel6.setText("Number of pictures:");
//
//        jLabel7.setText("You can press escape to stop any time...");
//
//        jTextField1.setText("1");
//
//        jLabel5.setText("Current Window:");
//        jLabel5.setToolTipText("");
//
//        cWindow.setText("0,0,0,0");
//
//        jLabel8.setText("Wait between each picture (ms):");
//
//        waitTime.setText("1000");
//
//        jCheckBox1.setSelected(true);
//        jCheckBox1.setText("Doc the mouse between clicks");
//
//        jLabel9.setText("(The number of pages after the current page you want taken.)");
//
//        jButton2.setText("Show Window");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jLabel10.setText("Name:");
//
//        name.setText("New Ebook");
//
//        jLabel11.setText("(This must be long enough for the read to turn the page.)");
//
//        checkForDuplicates.setSelected(true);
//        checkForDuplicates.setText("Try to check for duplicates");
//
//        jLabel12.setText("Image extensions:");
//
//        jComboBox1.setModel(model);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(jLabel6)
//                        .addGap(18, 18, 18)
//                        .addComponent(jTextField1))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(cSavePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGap(91, 91, 91))
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                .addGap(0, 0, Short.MAX_VALUE)
//                                .addComponent(change))))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(0, 0, Short.MAX_VALUE)
//                                .addComponent(dragFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel2)
//                                .addGap(18, 18, 18)
//                                .addComponent(cClickPosition)
//                                .addGap(0, 0, Short.MAX_VALUE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel1)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(mouseDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(18, 18, 18)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(jLabel5)
//                        .addGap(18, 18, 18)
//                        .addComponent(cWindow)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(jButton2))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(jLabel8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(0, 0, Short.MAX_VALUE)
//                                .addComponent(jLabel9))
//                            .addComponent(waitTime)))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(jLabel10)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(name))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addComponent(jLabel11))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(checkForDuplicates)
//                            .addComponent(overwrite))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel12)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                            .addComponent(jLabel7))))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(5, 5, 5)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel4)
//                            .addComponent(cSavePath)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(change)))
//                .addGap(9, 9, 9)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel2)
//                            .addComponent(cClickPosition))
//                        .addGap(14, 14, 14)
//                        .addComponent(jLabel1))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel3)
//                            .addComponent(dragFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jCheckBox1)
//                            .addComponent(mouseDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                .addGap(10, 10, 10)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jButton2)
//                    .addComponent(jLabel5)
//                    .addComponent(cWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel6))
//                .addGap(18, 18, 18)
//                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(waitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel8))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(jLabel11)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel10))
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel12)
//                    .addComponent(overwrite))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(checkForDuplicates)
//                    .addComponent(jLabel7))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addContainerGap())
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//	private void dragFromMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFromMouseDragged
//		clickLoc = evt.getLocationOnScreen();
//		cClickPosition.setText(clickLoc.x + ", " + clickLoc.y);
//	}//GEN-LAST:event_dragFromMouseDragged
//
//	private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
//		final JFileChooser chooser = new JFileChooser();
//		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//		if (chooser.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
//			return;
//		}
//		try {
//			cSavePath.setText(chooser.getSelectedFile().getCanonicalPath());
//		} catch (Exception e) {
//			Driver.handleException("Could not open that diretory!", e, false);
//		}
//	}//GEN-LAST:event_changeActionPerformed
//
//	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//
//            BookProps props = new BookProps();
//            write(props);
//            Driver.savePictures(props);
//
//	}//GEN-LAST:event_jButton1ActionPerformed
//
//	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//		Driver.showWindow();
//	}//GEN-LAST:event_jButton2ActionPerformed
//        
//        
//        
//        
//        
//        void read(BookProps props)
//        {
//            cSavePath.setText(props.location);
//            jTextField1.setText(String.valueOf(props.times));
//            waitTime.setText(String.valueOf(props.wait));
//            clickLoc = props.turnPage;
//            name.setText(props.bookName);
//        }
//        
//        void write(BookProps props)
//        {
//                props.location = cSavePath.getText();
//		if (props.location.equals("")) {
//			Driver.handleException("You must choose a location!", null, false);
//			return;
//		}
//		String num = jTextField1.getText();
//		try {
//			props.times = new Integer(num);
//			if (props.times < 0) {
//				throw new Exception("The number of times to save"
//						+ " can not be negative!");
//			}
//		} catch (Exception e) {
//			Driver.handleException("Invalid number of times: \""
//					+ num + "\" to save.",
//					e, false);
//			return;
//		}
//
//		num = waitTime.getText();
//		try {
//			props.wait = new Long(num);
//			if (props.wait < 0) {
//				throw new Exception("The wait time can not be negative!");
//			}
//		} catch (Exception e) {
//			Driver.handleException("Invalid wait time: \"" + num + "\".",
//					e, false);
//			return;
//		}
//
//		props.turnPage = this.clickLoc;
//		if (props.turnPage.x < 0 || props.turnPage.y < 0) {
//			Driver.handleException("Plase specify a place to click to turn the"
//					+ " page",
//					null, false);
//			return;
//		}
//                
//                props.overwrite = overwrite.isSelected();
//                props.docMouse = jCheckBox1.isSelected();
//                props.check = checkForDuplicates.isSelected();
//                props.filetype = (String) jComboBox1.getSelectedItem();
//
//		props.bookName = name.getText();
//		if (props.bookName.equals("") || !Pattern.matches("[a-zA-Z0-9 ,_-]*", props.bookName)) {
//			Driver.handleException("The name must only consist of letters, "
//					+ "numbers, spaces, commas, underscores, or dashes!", null,
//					false);
//			return;
//		}
//        }
//        
//        
//        
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JLabel cClickPosition;
//    private javax.swing.JLabel cSavePath;
//    private javax.swing.JLabel cWindow;
//    private javax.swing.JButton change;
//    private javax.swing.JCheckBox checkForDuplicates;
//    private javax.swing.JPanel dragFrom;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JCheckBox jCheckBox1;
//    private javax.swing.JComboBox jComboBox1;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JPanel mouseDoc;
//    private javax.swing.JTextField name;
//    private javax.swing.JCheckBox overwrite;
//    private javax.swing.JTextField waitTime;
//    // End of variables declaration//GEN-END:variables
//}
