/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package files.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedList;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import files.app.Application;
import files.app.Logger.LogLevel;
import files.app.TemplateManager.Template;
import files.app.TemplateManager.TemplatesListener;
import files.util.ComponentShowingListener;

/**
 *
 * @author thallock
 */
public class RootViewTemplates extends javax.swing.JPanel implements TemplatesListener {

	DefaultListModel<Template> list = new DefaultListModel<Template>();
	Template currentlyViewing;

	/**
	 * Creates new form TemplatesViewer
	 */
	public RootViewTemplates()
	{
		initComponents();

		createPopupMenu();

		RootViewTemplates t = this;
		new ComponentShowingListener(this)
		{
			@Override
			protected void isShowing()
			{
				templatesChanged();
				Application.getApplication().getTemplates().add(t);
			}

			@Override
			protected void isNotShowing()
			{
				Application.getApplication().getTemplates().remove(t);
			}
		};

		jList1.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent evt)
			{
				JList jList = (JList) evt.getSource();
				if (evt.getClickCount() != 2)
					return;
				int index = jList.locationToIndex(evt.getPoint());
				if (index < 0)
					return;
				Template fileType = list.get(index);
				if (fileType == null)
					return;
				select(fileType);
			}
		});

		templatesChanged();
	}

	private void createPopupMenu()
	{
		JPopupMenu menu = new JPopupMenu();
		JMenuItem item = new JMenuItem("Add new type");
		item.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				Template template = new Template("Unamed Template " + new Date(), "");
				Application.getApplication().getTemplates().addTemplate(template);
			}
		});
		menu.add(item);

		item = new JMenuItem("Delete Selected");
		item.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				LinkedList<Template> toDelete = new LinkedList<>();
				StringBuilder builder = new StringBuilder("Deleting ");
				int[] selectedIndices = jList1.getSelectedIndices();
				for (int i : selectedIndices)
				{
					Template elementAt = list.getElementAt(i);
					builder.append("\"").append(elementAt).append("\" ");
					toDelete.add(elementAt);
				}

				Application.getApplication().getTemplates().removeAll(toDelete);
			}
		});
		menu.add(item);
		jList1.setComponentPopupMenu(menu);
	}

	void select(Template newFileType)
	{
		if (newFileType == null || !Application.getApplication().getTemplates().hasTemplate(newFileType))
		{
			currentlyViewing = null;
			jTextField1.setText("");
			jTextField2.setText("");
			jButton1.setEnabled(false);
			jButton2.setEnabled(false);
			jTextField1.setEditable(false);
			jTextField2.setEditable(false);
		}
		else
		{
			currentlyViewing = newFileType;
			jTextField1.setText(newFileType.getDisplayName());
			jTextField2.setText(newFileType.getFileLocation());
			jButton1.setEnabled(true);
			jButton2.setEnabled(true);
			jTextField1.setEditable(true);
			jTextField2.setEditable(true);
		}
	}

	@Override
	public void templatesChanged()
	{
		list.removeAllElements();

		LinkedList<Template> fileTypes = new LinkedList<>();
		fileTypes.addAll(Application.getApplication().getTemplates().getTemplates());

		Collections.sort(fileTypes);
		fileTypes.stream().forEach(x -> list.addElement(x));

		select(currentlyViewing);
	}

	private DefaultListModel getListModel()
	{
		return list;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(300);

        jList1.setModel(getListModel());
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jLabel1.setText("Name:");

        jLabel2.setText("Template File:");

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update or Replace");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        try
	{
		chooser.setSelectedFile(Paths.get(Application.getApplication().getSettings().getTemplatesPath()).toRealPath().getParent().toFile());
	}
        catch (IOException e)
	{
                Application.getApplication().getLogger().log(LogLevel.Normal, "unable to set templates path", e);
	}
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
        {
            return;
        }
            try {
                jTextField2.setText(chooser.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {
                    Application.getApplication().getLogger().log(LogLevel.Normal, "unable to get file", ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Template newTemplate = new Template(jTextField1.getText(), jTextField2.getText());
        Application.getApplication().getTemplates().replace(
                currentlyViewing, newTemplate);
        select(newTemplate);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
